"""Phase 1 against Phase 0 for the CPU tier: goal test, before/after, memory, signatures.

Reads the Phase 0 baseline campaign and the Phase 1 campaign (both written by
``bench/runner.py --mode cpu-baseline``) and applies the decision rules of
``bench/cpu/PROTOCOL.md``:

- goal test: an F arm wins a regime against efficient-apriori (EA, Phase 1
  rows) when its median is >= 10 % below EA's, the [min, max] ranges do not
  overlap, and it saves >= 1 s (where EA's median is below 10 s the floor is
  10 % of EA's median);
- before/after: rule 2 against the same arm and thread setting of the
  baseline;
- memory: Phase 1 ``ru_maxrss_mb`` median within 1.25x of the baseline's;
- signatures: one itemset hash per workload across both campaigns.

Writes ``compare.md`` into the Phase 1 directory and prints a summary.

Usage:
    uv run python bench/cpu/compare.py bench/results/2026-10-07-cpu-baseline bench/results/2026-10-07-cpu-phase1

Options:
    BASELINE_DIR  Phase 0 results directory (raw.jsonl)
    PHASE1_DIR    Phase 1 results directory (raw.jsonl); compare.md is written here
"""

from __future__ import annotations

import json
import statistics
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from cpu.matrix import F_ARMS, THREADS, WORKLOADS  # noqa: E402


def _rows(d: Path) -> dict[str, list[dict]]:
    """{base_id: [ok rows]} keeping the last row per id."""
    latest = {}
    for line in (d / "raw.jsonl").read_text().splitlines():
        r = json.loads(line)
        latest[r["id"]] = r
    out: dict[str, list[dict]] = {}
    for r in latest.values():
        c = r.get("config", {})
        if c.get("mode") == "cpu" and r.get("status") == "ok":
            out.setdefault(c["base_id"], []).append(r)
    return out


def _stat(rows: list[dict], key: str = "wall_s") -> tuple[float, float, float, int] | None:
    vals = [r[key] for r in rows]
    if not vals:
        return None
    return statistics.median(vals), min(vals), max(vals), len(vals)


def _cell(st) -> str:
    if st is None:
        return "—"
    med, lo, hi, n = st
    return f"{med:.2f} (1 rep)" if n == 1 else f"{med:.2f} [{lo:.2f}, {hi:.2f}]"


def wins(new, old, floor_from_old: bool = False) -> bool:
    """Rule 2: new's median >= 10 % below old's, ranges apart, saving >= 1 s (or 10 % of a < 10 s old)."""
    if new is None or old is None:
        return False
    floor = 0.1 * old[0] if (floor_from_old and old[0] < 10) else 1.0
    return new[0] <= 0.9 * old[0] and new[2] < old[1] and old[0] - new[0] >= floor


def main() -> int:
    base, new = _rows(Path(sys.argv[1])), _rows(Path(sys.argv[2]))
    out = ["# CPU tier, Phase 1 against Phase 0", "",
           "Generated by `bench/cpu/compare.py`. Seconds, median [min, max]; EA from the Phase 1 campaign.", ""]

    out += ["## Goal test: F arms against efficient-apriori (rule 2, floor 10 % of EA below 10 s)", "",
            "| regime | EA | " + " | ".join(f"{a} {t}" for a in F_ARMS for t in THREADS) + " | wins |",
            "|---|---|" + "---|" * (len(F_ARMS) * len(THREADS) + 1)]
    goal_total = goal_won = 0
    for w in WORKLOADS:
        ea = _stat(new.get(f"{w}-EA", []))
        cells, won = [], []
        for a in F_ARMS:
            for t in THREADS:
                st = _stat(new.get(f"{w}-{a}-{t}", []))
                ok = wins(st, ea, floor_from_old=True)
                if a in ("F-polars", "F-auto"):
                    goal_total += 1
                    goal_won += ok
                cells.append(f"{_cell(st)} {'✓' if ok else '✗'}")
                won.append(ok)
        out.append(f"| {w} | {_cell(ea)} | " + " | ".join(cells) + f" | {sum(won)}/{len(won)} |")
    out += ["", f"Goal arms (F-polars, F-auto) win {goal_won} of {goal_total} regime cells.", ""]

    out += ["## Before / after (same arm and thread setting; rule 2 against Phase 0)", "",
            "| regime | arm | Phase 0 | Phase 1 | speed-up | rule 2 |", "|---|---|---|---|---|---|"]
    for w in WORKLOADS:
        for a in F_ARMS:
            for t in THREADS:
                b = f"{w}-{a}-{t}"
                o, n = _stat(base.get(b, [])), _stat(new.get(b, []))
                if n is None:
                    continue
                if o is None:
                    out.append(f"| {w} | {a} {t} | (cap hit, > 600) | {_cell(n)} | > {600 / n[0]:.0f}x | win |")
                    continue
                out.append(f"| {w} | {a} {t} | {_cell(o)} | {_cell(n)} | {o[0] / n[0]:.1f}x | "
                           f"{'win' if wins(n, o) else 'no'} |")
        oe, ne = _stat(base.get(f"{w}-EA", [])), _stat(new.get(f"{w}-EA", []))
        out.append(f"| {w} | EA | {_cell(oe)} | {_cell(ne)} | {oe[0] / ne[0]:.2f}x | (same code) |"
                   if oe and ne else f"| {w} | EA | {_cell(oe)} | {_cell(ne)} | — | |")
    out.append("")

    out += ["## Memory: ru_maxrss median (MB), Phase 1 against 1.25x Phase 0", "",
            "| regime | arm | Phase 0 | Phase 1 | ratio | within 25 % |", "|---|---|---|---|---|---|"]
    over = []
    for w in WORKLOADS:
        for a in F_ARMS:
            for t in THREADS:
                b = f"{w}-{a}-{t}"
                o, n = _stat(base.get(b, []), "ru_maxrss_mb"), _stat(new.get(b, []), "ru_maxrss_mb")
                if o is None or n is None:
                    continue
                ok = n[0] <= 1.25 * o[0]
                if not ok:
                    over.append(b)
                out.append(f"| {w} | {a} {t} | {o[0]:.0f} | {n[0]:.0f} | {n[0] / o[0]:.2f} | {'yes' if ok else 'NO'} |")
    out += ["", f"Over the 25 % rule: {', '.join(over) or 'none'}.", ""]

    out += ["## Signatures", "", "| workload | Phase 0 | Phase 1 | equal |", "|---|---|---|---|"]
    for w in WORKLOADS:
        h0 = {r["itemset_hash"] for b, rs in base.items() if b.startswith(w + "-") for r in rs}
        h1 = {r["itemset_hash"] for b, rs in new.items() if b.startswith(w + "-") for r in rs}
        out.append(f"| {w} | {', '.join(sorted(h[:12] for h in h0))} | {', '.join(sorted(h[:12] for h in h1))} | "
                   f"{'yes' if h0 == h1 and len(h1) == 1 else 'NO'} |")
    out.append("")

    out += ["## Where the time goes now (F-auto, median rep; seconds summed over levels)", "",
            "| regime | wall | matrix_build | k2_gram | k2_bitvec | bitvec_build | count | subsets | other | emit |",
            "|---|---|---|---|---|---|---|---|---|---|"]
    for w in WORKLOADS:
        for t in THREADS:
            rs = sorted(new.get(f"{w}-F-auto-{t}", []), key=lambda r: r["wall_s"])
            if not rs:
                continue
            r = rs[(len(rs) - 1) // 2]
            sp = r["timings"].get("split") or {}
            tot = {p: sum(v.get(p, 0.0) for v in sp.values()) for p in
                   ("matrix_build", "k2_gram", "k2_bitvec", "bitvec_build", "count", "subsets", "other")}
            emit = (r["timings"].get("tail") or {}).get("emit", 0.0)
            out.append(f"| {w} {t} | {r['wall_s']:.2f} | " + " | ".join(f"{tot[p]:.2f}" for p in tot) + f" | {emit:.2f} |")
    out.append("")
    path = Path(sys.argv[2]) / "compare.md"
    path.write_text("\n".join(out) + "\n")
    print(f"wrote {path}; goal arms win {goal_won}/{goal_total}; memory over 25 %: {over or 'none'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
